spring:
  redis:
    database: 0
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/study
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver